# Generated by Django 3.0.6 on 2020-05-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='event_images/event_placeholder.png', upload_to='event_images/'),
        ),
    ]
