# Generated by Django 3.0.6 on 2020-05-30 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20200530_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date']},
        ),
    ]
