# Generated by Django 3.0.6 on 2020-06-03 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20200602_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgoer',
            name='eventBuddy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.EventGoer'),
        ),
    ]
