# Generated by Django 3.0.6 on 2020-06-03 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_eventgoer_eventbuddy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventgoer',
            name='eventBuddy',
        ),
    ]
