# Generated by Django 3.0.6 on 2020-06-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_auto_20200603_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(max_length=1000)),
                ('quantity', models.IntegerField(default=0)),
                ('image', models.ImageField(default='rewards_images/reward_placeholder.svg', upload_to='rewards_images/')),
            ],
        ),
    ]
