# Generated by Django 3.0.6 on 2020-06-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='pointsNeeded',
            field=models.IntegerField(default=1),
        ),
    ]
