# Generated by Django 3.0.6 on 2020-06-05 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200605_2150'),
        ('system', '0016_rewarder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewarder',
            name='withdrawer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
