# Generated by Django 3.0.6 on 2020-06-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0017_auto_20200605_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgoer',
            name='chatName',
            field=models.CharField(default='', max_length=120),
        ),
    ]
