# Generated by Django 3.0.6 on 2020-06-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0018_eventgoer_chatname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgoer',
            name='chatName',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
    ]
