# Generated by Django 3.0.6 on 2020-06-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0020_auto_20200611_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgoer',
            name='chatName',
            field=models.CharField(default='', max_length=120),
        ),
    ]
