# Generated by Django 3.0.6 on 2020-06-16 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0022_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedPerson',
            fields=[
                ('ipAddress', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recommendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.EventGoer')),
            ],
        ),
    ]
