# Generated by Django 3.0.6 on 2020-06-16 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0023_recommendedperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendedperson',
            name='recommendor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.EventGoer'),
        ),
    ]
