# Generated by Django 3.0.6 on 2020-06-18 19:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0024_auto_20200616_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='timeSent',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recommendedperson',
            name='recommendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='system.EventGoer'),
            preserve_default=False,
        ),
    ]
