# Generated by Django 3.0.6 on 2020-06-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200605_2150'),
        ('system', '0025_auto_20200618_2104'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rewarder',
            new_name='RewardWithdrawer',
        ),
        migrations.AlterField(
            model_name='eventgoer',
            name='chatName',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
