# Generated by Django 3.0.6 on 2020-07-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200605_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sendCreditInfo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sendEventUpdates',
            field=models.BooleanField(default=False),
        ),
    ]
